# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Testing CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.16.1
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.1

      - run: yarn install --immutable

      - run: yarn workspaces foreach run test-ci

      - run: yarn lint

      #####
      # Currently not working for forks pull requests. Github checkout action
      # does only merged commit so forked head is not available for compare.
      #####
      # - name: lint changeset
      # run: |
      # Checkout PR head commit instead of merge commit
      # See: https://github.com/atlassian/changesets/issues/517
      # git fetch origin ${GITHUB_HEAD_REF}
      # git fetch origin ${GITHUB_BASE_REF}
      # git checkout ${GITHUB_HEAD_REF}
      # yarn changeset status --since=origin/${GITHUB_BASE_REF}
      # git checkout ${GITHUB_SHA}
      # if: ${{ github.event_name == 'pull_request' }}

      # - run: yarn merge-reports
      # - uses: IgnusG/jest-report-action@v2.3.3
      #if: always() # Or use "continue-on-error: true" in previous test step
      #with:
      # access-token: ${{ secrets.GITHUB_TOKEN }}
